version: 2
sources:
  - name: TEST_SOURCE
    description: This is RAW_TEST Database Source Tables used for creating STANDARD_TEST Layer
    database: TEST_DB
    tables:
      - name: CUSTOMER
      - name: ORDERS
  - name: STAGE
    description: This is RAW_TEST Database Source Tables used for creating STANDARD_TEST Layer
    database: TEST_DB
    tables:
      - name: CUSTOMER
      - name: ORDERS